[template]
ignore = ["target"]

[placeholders.gh_user]
type = "string"
prompt = "What is your Github Username?"
default = "AliSajid"

[placeholders.msrv]
type = "string"
prompt = "What is your Minimum Supported Rust Version?"
default = "1.62.0"

[placeholders.include_security_email]
type = "bool"
prompt = "Do you want to include a security email?"
default = false

[placeholders.include_license]
type = "bool"
prompt = "Do you want to include a license?"
default = false

[placeholders.project-description]
type = "string"
prompt = "What is your project description?"
default = "A new project"

[placeholders.dynamic-badge-gist]
type = "string"
prompt = "What is your Gist ID for the dynamic badge workflow?"

[conditional.'!include_license']
ignore = ["LICENSE-APACHE", "LICENSE-MIT", "LICENSE-GPL-v3.0", "meta/LICENSE-HEADER"]

[conditional.'include_security_email'.placeholders.security_email]
type = "string"
prompt = "What is your security email?"

[conditional.'include_license'.placeholders.license]
type = "string"
prompt = "What is your license?"
choices = ["MIT", "Apache-2.0", "GPL-3.0", "Dual MIT/Apache-2.0"]
default = "Dual MIT/Apache-2.0"

[conditional.'license == "MIT"']
ignore = ["LICENSE-APACHE", "LICENSE-GPL-v3.0"]

[conditional.'license == "Apache-2.0"']
ignore = ["LICENSE-MIT", "LICENSE-GPL-v3.0"]

[conditional.'license == "GPL-3.0"']
ignore = ["LICENSE-MIT", "LICENSE-APACHE"]

[conditional.'license == "Dual MIT/Apache-2.0"']
ignore = ["LICENSE-GPL-v3.0"]
