# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[template]
ignore = ["target"]

[hooks]
init = ["project_setup.rhai"]

[placeholders.gh_user]
type = "string"
prompt = "What is your Github Username?"
default = "AliSajid"

[placeholders.license]
type = "string"
prompt = "What is your license?"
choices = ["MIT", "Apache-2.0", "GPL-3.0", "Dual MIT/Apache-2.0", "None"]
default = "Dual MIT/Apache-2.0"

[placeholders.msrv]
type = "string"
prompt = "What is your Minimum Supported Rust Version?"
default = "1.64.0"

[placeholders.include_security_email]
type = "bool"
prompt = "Do you want to include a security email?"
default = false

[placeholders.project-description]
type = "string"
prompt = "What is your project description?"
default = "A new project"

[placeholders.dynamic-badge-gist]
type = "string"
prompt = "What is your Gist ID for the dynamic badge workflow?"
