version = 1
SPDX-PackageName = "aaprop"
SPDX-PackageSupplier = "Ali Sajid Imami <Ali.Sajid.Imami@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/AliSajid/aaprop"

[[annotations]]
path = [
    ".gitignore",
    "guide/.gitignore",
    ".gitleaksignore",
    ".markdownlintignore",
    ".markdownlint.json",
    ".secrets.baseline",
    ".vscode/**.json",
    "meta/vale-styles/config/**/**.txt",
    "CHANGELOG.md",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["Cargo.lock", "renovate.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "MIT AND Apache-2.0"

[[annotations]]
path = "licenses_report.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "Apache-2.0 AND MIT"

[[annotations]]
path = ["guide/book.toml", "guide/src/*.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "MIT AND Apache-2.0"
